language: python

python: 3.6

matrix:
  include:
    - name: Rust Stable
      env: RUST_TOOLCHAIN="stable"
    - name: Rust Beta
      env: RUST_TOOLCHAIN="beta"

install:
  - pip install svdtools
  - cd stm32-rs/svd && ./extract.sh && cd ../..
  - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain=$RUST_TOOLCHAIN
  - export PATH="$HOME/.cargo/bin:$PATH"
  - rustup component add rustfmt

script:
  - make -j2
  - git update-index --refresh
  - git diff-files --exit-code
  - test -z "$(git ls-files --exclude-standard --others)"
  - make buildall
  - cargo test --doc --features stm32f405
